import { Stadium } from '@/lib/types/stadium'
import { getTeamById } from './teams'

export const K_LEAGUE_FULL_STADIUMS: Stadium[] = [
  // K리그1 경기장 (2025시즌 - 12개 팀)
  {
    id: 'stadium-seoul',
    name: '서울 월드컵',
    fullName: '서울월드컵경기장',
    displayLine1: '서울',
    displayLine2: '월드컵',
    teamId: 'fc-seoul',
    location: { lat: 37.568288, lng: 126.897273 },
    address: '서울 마포구 월드컵로 240',
  },
  {
    id: 'stadium-ulsan',
    name: '울산 문수',
    fullName: '울산문수축구경기장',
    displayLine1: '울산',
    displayLine2: '문수',
    teamId: 'ulsan',
    location: { lat: 35.535267, lng: 129.259532 },
    address: '울산 남구 문수로 44',
  },
  {
    id: 'stadium-jeonbuk',
    name: '전주 월드컵',
    fullName: '전주월드컵경기장',
    displayLine1: '전주',
    displayLine2: '월드컵',
    teamId: 'jeonbuk',
    location: { lat: 35.868089, lng: 127.064478 },
    address: '전북 전주 덕진구 기린대로 1055',
  },
  {
    id: 'stadium-pohang',
    name: '포항 스틸야드',
    fullName: '포항스틸야드',
    displayLine1: '포항',
    displayLine2: '스틸야드',
    teamId: 'pohang',
    location: { lat: 35.997717, lng: 129.384436 },
    address: '경북 포항시 남구 동해안로6213번길 20',
  },
  {
    id: 'stadium-gwangju',
    name: '광주 월드컵',
    fullName: '광주월드컵경기장',
    displayLine1: '광주',
    displayLine2: '월드컵',
    teamId: 'gwangju',
    location: { lat: 35.133646, lng: 126.874830 },
    address: '광주 서구 금화로 240',
  },
  {
    id: 'stadium-gangneung',
    name: '강릉하이원아레나',
    fullName: '강릉하이원아레나',
    displayLine1: '강릉',
    displayLine2: '아레나',
    teamId: 'gangneung',
    location: { lat: 37.773679, lng: 128.898418 },
    address: '강원 강릉시 종합운동장길 69',
  },
  {
    id: 'stadium-gimcheon',
    name: '김천 종합',
    fullName: '김천종합운동장',
    displayLine1: '김천',
    displayLine2: '종합',
    teamId: 'gimcheon',
    location: { lat: 36.139694, lng: 128.086502 },
    address: '경북 김천시 운동장길 1',
  },
  {
    id: 'stadium-jeju',
    name: '제주 월드컵',
    fullName: '제주월드컵경기장',
    displayLine1: '제주',
    displayLine2: '월드컵',
    teamId: 'jeju',
    location: { lat: 33.246219, lng: 126.509275 },
    address: '제주 서귀포 월드컵로 33',
  },
  {
    id: 'stadium-daejeon',
    name: '대전 월드컵',
    fullName: '대전월드컵경기장',
    displayLine1: '대전',
    displayLine2: '월드컵',
    teamId: 'daejeon',
    location: { lat: 36.361966, lng: 127.323555 },
    address: '대전 유성구 월드컵대로 32',
  },
  {
    id: 'stadium-anyang',
    name: '안양 종합',
    fullName: '안양종합운동장',
    displayLine1: '안양',
    displayLine2: '종합',
    teamId: 'anyang',
    location: { lat: 37.406291, lng: 126.948737 },
    address: '경기 안양시 동안구 평촌대로 389',
  },
  {
    id: 'stadium-incheon',
    name: '인천 전용',
    fullName: '인천축구전용경기장',
    displayLine1: '인천',
    displayLine2: '전용',
    teamId: 'incheon',
    location: { lat: 37.467394, lng: 126.642622 },
    address: '인천 중구 참외전로 246',
  },
  {
    id: 'stadium-bucheon',
    name: '부천 종합',
    fullName: '부천종합운동장',
    displayLine1: '부천',
    displayLine2: '종합',
    teamId: 'bucheon',
    location: { lat: 37.502194, lng: 126.798946 },
    address: '경기 부천시 원미구 소사로 482',
  },

  // K리그2 경기장 (2025시즌 - 15개 팀)
  {
    id: 'stadium-busan',
    name: '부산아시아드주경기장',
    displayLine1: '부산',
    displayLine2: '아시아드',
    teamId: 'busan',
    location: { lat: 35.190087, lng: 129.058356 },
    address: '부산 연제구 월드컵대로 344',
  },
  {
    id: 'stadium-suwon-fc',
    name: '수원종합운동장',
    displayLine1: '수원',
    displayLine2: '종합',
    teamId: 'suwon-fc',
    location: { lat: 37.297843, lng: 127.011348 },
    address: '경기 수원 장안구 경수대로 893',
  },
  {
    id: 'stadium-suwon-bluewings',
    name: '수원월드컵경기장',
    displayLine1: '수원',
    displayLine2: '월드컵',
    teamId: 'suwon-bluewings',
    location: { lat: 37.286423, lng: 127.035967 },
    address: '경기 수원 팔달구 월드컵로 310',
  },
  {
    id: 'stadium-cheonan',
    name: '천안종합운동장',
    displayLine1: '천안',
    displayLine2: '종합',
    teamId: 'cheonan',
    location: { lat: 36.819101, lng: 127.113305 },
    address: '충남 천안 서북구 번영로 208',
  },
  {
    id: 'stadium-gyeongnam',
    name: '창원축구센터',
    displayLine1: '창원',
    displayLine2: '축구',
    teamId: 'gyeongnam',
    location: { lat: 35.223790, lng: 128.707103 },
    address: '경남 창원 성산구 비음로 97',
  },
  {
    id: 'stadium-seoul-eland',
    name: '목동종합운동장',
    displayLine1: '목동',
    displayLine2: '종합',
    teamId: 'seoul-eland',
    location: { lat: 37.530728, lng: 126.879233 },
    address: '서울 양천구 안양천로 939',
  },
  {
    id: 'stadium-jeonnam',
    name: '광양축구전용구장',
    displayLine1: '광양',
    displayLine2: '축구',
    teamId: 'jeonnam',
    location: { lat: 34.933079, lng: 127.727461 },
    address: '전남 광양시 백운로 1641',
  },
  {
    id: 'stadium-yongin',
    name: '용인미르스타디움',
    displayLine1: '용인',
    displayLine2: '미르',
    teamId: 'yongin',
    location: { lat: 37.249631, lng: 127.165158 },
    address: '경기 용인 처인구 동백죽전대로 61',
  },
  {
    id: 'stadium-gimhae',
    name: '김해운동장',
    displayLine1: '김해',
    displayLine2: '운동장',
    teamId: 'gimhae',
    location: { lat: 35.255534, lng: 128.877094 },
    address: '경남 김해시 가야로 245',
  },
  {
    id: 'stadium-hwaseong',
    name: '화성종합경기타운',
    displayLine1: '화성',
    displayLine2: '종합',
    teamId: 'hwaseong',
    location: { lat: 37.137471, lng: 126.924665 },
    address: '경기 화성 향남읍 향남로 470',
  },
  {
    id: 'stadium-paju',
    name: '파주스타디움',
    displayLine1: '파주',
    displayLine2: '스타디움',
    teamId: 'paju',
    location: { lat: 37.756141, lng: 126.785768 },
    address: '경기 파주시 중앙로 160',
  },
  {
    id: 'stadium-chungbuk',
    name: '청주종합운동장',
    displayLine1: '청주',
    displayLine2: '종합',
    teamId: 'chungbuk',
    location: { lat: 36.637856, lng: 127.472345 },
    address: '충북 청주시 서원구 사직대로 229',
  },
  {
    id: 'stadium-asan',
    name: '이순신종합운동장',
    displayLine1: '아산',
    displayLine2: '종합',
    teamId: 'asan',
    location: { lat: 36.768176, lng: 127.020724 },
    address: '충남 아산시 남부로 370-24',
  },
  {
    id: 'stadium-seongnam',
    name: '탄천종합운동장',
    displayLine1: '성남',
    displayLine2: '탄천',
    teamId: 'seongnam',
    location: { lat: 37.411791, lng: 127.120513 },
    address: '경기 성남시 분당구 탄천로 215',
  },
  {
    id: 'stadium-ansan',
    name: '안산와~스타디움',
    displayLine1: '안산',
    displayLine2: '스타디움',
    teamId: 'ansan',
    location: { lat: 37.319478, lng: 126.816492 },
    address: '경기 안산 단원구 화랑로 260',
  },
  {
    id: 'stadium-gimpo',
    name: '김포솔터축구장',
    displayLine1: '김포',
    displayLine2: '솔터',
    teamId: 'gimpo',
    location: { lat: 37.640600, lng: 126.648289 },
    address: '경기 김포시 김포한강3로 387',
  },
]

// Stadium에 Team 정보 매핑
export function getStadiumWithTeam(stadium: Stadium) {
  return {
    ...stadium,
    team: getTeamById(stadium.teamId),
  }
}

// 모든 Stadium에 Team 정보 포함
export const K_LEAGUE_STADIUMS_WITH_TEAMS = K_LEAGUE_FULL_STADIUMS.map(getStadiumWithTeam)
