import { Team } from '@/lib/types/team'

export const K_LEAGUE_TEAMS: Team[] = [
  // K리그1 팀
  {
    id: 'fc-seoul',
    name: 'FC서울',
    shortName: '서울',
    displayLine1: '서울',
    primaryColor: '#C8102E',
    secondaryColor: '#000000',
    uniformPattern: 'vertical-stripe',
    leagueType: 1,
    officialUrl: 'http://www.fcseoul.com/',
  },
  {
    id: 'ulsan',
    name: '울산HD',
    shortName: '울산',
    displayLine1: '울산',
    primaryColor: '#0066B3',
    secondaryColor: '#FFD700',
    uniformPattern: 'vertical-stripe',
    leagueType: 1,
    officialUrl: 'https://www.uhdfc.com/',
  },
  {
    id: 'jeonbuk',
    name: '전북현대모터스',
    shortName: '전북',
    displayLine1: '전북',
    primaryColor: '#00A651',
    secondaryColor: '#000000',
    uniformPattern: 'solid',
    leagueType: 1,
    officialUrl: 'http://www.hyundai-motorsfc.com',
  },
  {
    id: 'pohang',
    name: '포항스틸러스',
    shortName: '포항',
    displayLine1: '포항',
    primaryColor: '#000000',
    secondaryColor: '#E2231A',
    uniformPattern: 'horizontal-stripe',
    leagueType: 1,
    officialUrl: 'http://www.steelers.co.kr',
  },
  {
    id: 'gwangju',
    name: '광주FC',
    shortName: '광주',
    displayLine1: '광주',
    primaryColor: '#FFD700',
    secondaryColor: '#FF0000',
    uniformPattern: 'diagonal-stripe',
    leagueType: 1,
    officialUrl: 'http://www.gwangjufc.com/',
  },
  {
    id: 'gangneung',
    name: '강릉FC',
    shortName: '강릉',
    displayLine1: '강릉',
    primaryColor: '#FF6B00',
    secondaryColor: '#FFFFFF',
    uniformPattern: 'solid',
    leagueType: 1,
    officialUrl: 'http://www.gangwon-fc.com',
  },
  {
    id: 'gimcheon',
    name: '김천상무',
    shortName: '김천',
    displayLine1: '김천',
    primaryColor: '#C8102E',
    secondaryColor: '#003478',
    uniformPattern: 'solid',
    leagueType: 1,
    officialUrl: 'http://gimcheonfc.com/',
  },
  {
    id: 'jeju',
    name: '제주SK',
    shortName: '제주',
    displayLine1: '제주',
    primaryColor: '#FF6600',
    secondaryColor: '#000000',
    uniformPattern: 'solid',
    leagueType: 1,
    officialUrl: 'http://www.jeju-utd.com',
  },
  {
    id: 'daejeon',
    name: '대전하나시티즌',
    shortName: '대전',
    displayLine1: '대전',
    primaryColor: '#702F8A',
    secondaryColor: '#FFFFFF',
    uniformPattern: 'solid',
    leagueType: 1,
    officialUrl: 'https://www.dhcfc.kr/',
  },
  {
    id: 'anyang',
    name: '안양FC',
    shortName: '안양',
    displayLine1: '안양',
    primaryColor: '#6C2785',
    secondaryColor: '#FFFFFF',
    uniformPattern: 'solid',
    leagueType: 1,
    officialUrl: 'http://www.fc-anynag.com',
  },
  {
    id: 'incheon',
    name: '인천유나이티드',
    shortName: '인천',
    displayLine1: '인천',
    primaryColor: '#000000',
    secondaryColor: '#0066B3',
    uniformPattern: 'vertical-stripe',
    leagueType: 1,
    officialUrl: 'http://www.incheonutd.com',
  },
  {
    id: 'bucheon',
    name: '부천FC1995',
    shortName: '부천',
    displayLine1: '부천',
    displayLine2: 'FC',
    primaryColor: '#C8102E',
    secondaryColor: '#000000',
    uniformPattern: 'horizontal-stripe',
    leagueType: 1,
    officialUrl: 'http://www.bfc1995.com',
  },

  // K리그2 팀
  {
    id: 'busan',
    name: '부산아이파크',
    shortName: '부산',
    displayLine1: '부산',
    primaryColor: '#C8102E',
    secondaryColor: '#FFFFFF',
    uniformPattern: 'solid',
    leagueType: 2,
    officialUrl: 'http://www.busanipark.com',
  },
  {
    id: 'suwon-fc',
    name: '수원FC',
    shortName: '수원FC',
    displayLine1: '수원',
    displayLine2: 'FC',
    primaryColor: '#E31837',
    secondaryColor: '#0033A0',
    uniformPattern: 'vertical-stripe',
    leagueType: 2,
    officialUrl: 'http://www.suwonfc.com',
  },
  {
    id: 'suwon-bluewings',
    name: '수원삼성블루윙즈',
    shortName: '삼성',
    displayLine1: '수원',
    displayLine2: '삼성',
    primaryColor: '#0066CC',
    secondaryColor: '#0066CC',
    uniformPattern: 'gradient',
    leagueType: 2,
    officialUrl: 'http://www.bluewings.kr/',
  },
  {
    id: 'cheonan',
    name: '천안시티FC',
    shortName: '천안',
    displayLine1: '천안',
    primaryColor: '#1E90FF',
    secondaryColor: '#FFFFFF',
    uniformPattern: 'solid',
    leagueType: 2,
    officialUrl: 'https://cheonancityfc.kr/',
  },
  {
    id: 'gyeongnam',
    name: '경남FC',
    shortName: '경남',
    displayLine1: '경남',
    primaryColor: '#FF0000',
    secondaryColor: '#000000',
    uniformPattern: 'solid',
    leagueType: 2,
    officialUrl: 'http://www.gyeongnamfc.com',
  },
  {
    id: 'seoul-eland',
    name: '서울이랜드FC',
    shortName: '서울E',
    displayLine1: '서울',
    displayLine2: '이랜드',
    primaryColor: '#003478',
    secondaryColor: '#FFD700',
    uniformPattern: 'solid',
    leagueType: 2,
    officialUrl: 'http://www.seoulelandfc.com',
  },
  {
    id: 'jeonnam',
    name: '전남드래곤즈',
    shortName: '전남',
    displayLine1: '전남',
    primaryColor: '#FFD700',
    secondaryColor: '#000000',
    uniformPattern: 'vertical-stripe',
    leagueType: 2,
    officialUrl: 'http://www.dragons.co.kr',
  },
  {
    id: 'yongin',
    name: '용인FC',
    shortName: '용인',
    displayLine1: '용인',
    primaryColor: '#FFD700',
    secondaryColor: '#800080',
    uniformPattern: 'diagonal-stripe',
    leagueType: 2,
    officialUrl: 'https://www.yonginfc.co.kr/',
  },
  {
    id: 'gimhae',
    name: '김해FC2008',
    shortName: '김해',
    displayLine1: '김해',
    primaryColor: '#0066B3',
    secondaryColor: '#FFFFFF',
    uniformPattern: 'solid',
    leagueType: 2,
    officialUrl: 'https://www.gimhaefc2008.com/',
  },
  {
    id: 'hwaseong',
    name: '화성FC',
    shortName: '화성',
    displayLine1: '화성',
    primaryColor: '#FF6600',
    secondaryColor: '#FFFFFF',
    uniformPattern: 'gradient',
    leagueType: 2,
    officialUrl: 'https://www.hwaseongfc.com/',
  },
  {
    id: 'paju',
    name: '파주프런티어FC',
    shortName: '파주',
    displayLine1: '파주',
    primaryColor: '#FF6600',
    secondaryColor: '#000000',
    uniformPattern: 'solid',
    leagueType: 2,
    officialUrl: 'http://fc.pajusports.co.kr/',
  },
  {
    id: 'chungbuk',
    name: '충북청주FC',
    shortName: '청주',
    displayLine1: '청주',
    primaryColor: '#E31837',
    secondaryColor: '#000000',
    uniformPattern: 'solid',
    leagueType: 2,
    officialUrl: 'http://chfc.kr/',
  },
  {
    id: 'asan',
    name: '충남아산FC',
    shortName: '아산',
    displayLine1: '아산',
    primaryColor: '#702F8A',
    secondaryColor: '#FFFFFF',
    uniformPattern: 'solid',
    leagueType: 2,
    officialUrl: 'https://www.asanfc.com',
  },
  {
    id: 'seongnam',
    name: '성남FC',
    shortName: '성남',
    displayLine1: '성남',
    primaryColor: '#FFD700',
    secondaryColor: '#000000',
    uniformPattern: 'solid',
    leagueType: 2,
    officialUrl: 'http://seongnamfc.com/',
  },
  {
    id: 'ansan',
    name: '안산그리너스',
    shortName: '안산',
    displayLine1: '안산',
    primaryColor: '#00A651',
    secondaryColor: '#FFFFFF',
    uniformPattern: 'solid',
    leagueType: 2,
    officialUrl: 'https://www.greenersfc.com/',
  },
  {
    id: 'gimpo',
    name: '김포FC',
    shortName: '김포',
    displayLine1: '김포',
    primaryColor: '#0066CC',
    secondaryColor: '#FFFFFF',
    uniformPattern: 'solid',
    leagueType: 2,
    officialUrl: 'https://www.gimpofc.com',
  },
]

export const getTeamById = (id: string): Team | undefined => {
  return K_LEAGUE_TEAMS.find(team => team.id === id)
}

export const getTeamByShortName = (shortName: string): Team | undefined => {
  return K_LEAGUE_TEAMS.find(team => team.shortName === shortName)
}
